### ISSUE TITLE
pre-commit error in github workflows: `GLIBC_2.39' not found

### ISSUE THREAD

**Issue by thiagowfx** [zimbatm/mdsh#74]
Recently:

```
mdsh.......................................................................................Failed
- hook id: mdsh
- exit code: 1

/home/runner/.cache/pre-commit/repok__zx1xb/rustenv-system/bin/mdsh: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.39' not found (required by /home/runner/.cache/pre-commit/repok__zx1xb/rustenv-system/bin/mdsh)
```

This is in a github workflow that runs the `mdsh` pre-commit hook:

```
# https://github.com/pre-commit/action
name: Pre-commit

permissions: read-all

on:
  pull_request:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
```

This is our pre-commit config: (snippet)

```
repos:
  - repo: https://github.com/zimbatm/mdsh.git
    rev: v0.9.0
    hooks:
      - id: mdsh
        types_or:
          - markdown
          - yaml
        always_run: true
```

I suspect this is related to https://github.com/actions/runner-images/issues/10636 ("Ubuntu-latest workflows will use Ubuntu-24.04 image"), because this setup was working fine for months until 2 days ago.

I couldn't find anything related in the bug tracker: https://github.com/zimbatm/mdsh/issues?q=GLIBC%20

Workarounds are welcome.
